# Project
version=2.6.0+mc26.1.2
group=com.ethan.voxyworldgenv2

# Minecraft
minecraft_version=26.1.2

# Fabric
fabric_api_version=0.147.0+26.1.2
loader_version=0.18.5
loom_version=1.15-SNAPSHOT

# Mod options
mod_name=Voxy World Gen V2
mod_author=iSeeEthan
mod_id=voxyworldgenv2

# Dependencies
cloth_config_version=26.1.154
mod_menu_version=18.0.0-alpha.8

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
