# Project
version=2.2.4
group=com.ethan.voxyworldgenv2

# Minecraft
minecraft_version=26.2

# Fabric
fabric_api_version=0.156.0+26.2
loader_version=0.19.3
loom_version=1.15-SNAPSHOT

# Mod options
mod_name=Voxy World Gen V2
mod_author=iSeeEthan
mod_id=voxyworldgenv2

# Dependencies
cloth_config_version=26.2.155
mod_menu_version=20.0.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
